Destination.create(country: "Afghanistan")
Destination.create(country: "Albania")
Destination.create(country: "Algeria")
Destination.create(country: "Andorra")
Destination.create(country: "Angola")
Destination.create(country: "Antigua & Deps")
Destination.create(country: "Argentina")
Destination.create(country: "Armenia")
Destination.create(country: "Australia")
Destination.create(country: "Austria")
Destination.create(country: "Azerbaijan")
Destination.create(country: "Bahamas")
Destination.create(country: "Bahrain")
Destination.create(country: "Bangladesh")
Destination.create(country: "Barbados")
Destination.create(country: "Belarus")
Destination.create(country: "Belgium")
Destination.create(country: "Belize")
Destination.create(country: "Benin")
Destination.create(country: "Bhutan")
Destination.create(country: "Bolivia")
Destination.create(country: "Bosnia Herzegovina")
Destination.create(country: "Botswana")
Destination.create(country: "Brazil")
Destination.create(country: "Brunei")
Destination.create(country: "Bulgaria")
Destination.create(country: "Burkina")
Destination.create(country: "Burundi")
Destination.create(country: "Cambodia")
Destination.create(country: "Cameroon")
Destination.create(country: "Canada")
Destination.create(country: "Cape Verde")
Destination.create(country: "Central African Rep")
Destination.create(country: "Chad")
Destination.create(country: "Chile")
Destination.create(country: "China")
Destination.create(country: "Colombia")
Destination.create(country: "Comoros")
Destination.create(country: "Congo")
Destination.create(country: "Congo {Democratic Rep}")
Destination.create(country: "Costa Rica")
Destination.create(country: "Croatia")
Destination.create(country: "Cuba")
Destination.create(country: "Cyprus")
Destination.create(country: "Czech Republic")
Destination.create(country: "Denmark")
Destination.create(country: "Djibouti")
Destination.create(country: "Dominica")
Destination.create(country: "Dominican Republic")
Destination.create(country: "East Timor")
Destination.create(country: "Ecuador")
Destination.create(country: "Egypt")
Destination.create(country: "El Salvador")
Destination.create(country: "Equatorial Guinea")
Destination.create(country: "Eritrea")
Destination.create(country: "Estonia")
Destination.create(country: "Ethiopia")
Destination.create(country: "Fiji")
Destination.create(country: "Finland")
Destination.create(country: "France")
Destination.create(country: "Gabon")
Destination.create(country: "Gambia")
Destination.create(country: "Georgia")
Destination.create(country: "Germany")
Destination.create(country: "Ghana")
Destination.create(country: "Greece")
Destination.create(country: "Grenada")
Destination.create(country: "Guatemala")
Destination.create(country: "Guinea")
Destination.create(country: "Guinea-Bissau")
Destination.create(country: "Guyana")
Destination.create(country: "Haiti")
Destination.create(country: "Honduras")
Destination.create(country: "Hungary")
Destination.create(country: "Iceland")
Destination.create(country: "India")
Destination.create(country: "Indonesia")
Destination.create(country: "Iran")
Destination.create(country: "Iraq")
Destination.create(country: "Ireland {Republic}")
Destination.create(country: "Israel")
Destination.create(country: "Italy")
Destination.create(country: "Ivory Coast")
Destination.create(country: "Jamaica")
Destination.create(country: "Japan")
Destination.create(country: "Jordan")
Destination.create(country: "Kazakhstan")
Destination.create(country: "Kenya")
Destination.create(country: "Kiribati")
Destination.create(country: "Korea North")
Destination.create(country: "Korea South")
Destination.create(country: "Kosovo")
Destination.create(country: "Kuwait")
Destination.create(country: "Kyrgyzstan")
Destination.create(country: "Laos")
Destination.create(country: "Latvia")
Destination.create(country: "Lebanon")
Destination.create(country: "Lesotho")
Destination.create(country: "Liberia")
Destination.create(country: "Libya")
Destination.create(country: "Liechtenstein")
Destination.create(country: "Lithuania")
Destination.create(country: "Luxembourg")
Destination.create(country: "Macedonia")
Destination.create(country: "Madagascar")
Destination.create(country: "Malawi")
Destination.create(country: "Malaysia")
Destination.create(country: "Maldives")
Destination.create(country: "Mali")
Destination.create(country: "Malta")
Destination.create(country: "Marshall Islands")
Destination.create(country: "Mauritania")
Destination.create(country: "Mauritius")
Destination.create(country: "Mexico")
Destination.create(country: "Micronesia")
Destination.create(country: "Moldova")
Destination.create(country: "Monaco")
Destination.create(country: "Mongolia")
Destination.create(country: "Montenegro")
Destination.create(country: "Morocco")
Destination.create(country: "Mozambique")
Destination.create(country: "Myanmar, {Burma}")
Destination.create(country: "Namibia")
Destination.create(country: "Nauru")
Destination.create(country: "Nepal")
Destination.create(country: "Netherlands")
Destination.create(country: "New Zealand")
Destination.create(country: "Nicaragua")
Destination.create(country: "Niger")
Destination.create(country: "Nigeria")
Destination.create(country: "Norway")
Destination.create(country: "Oman")
Destination.create(country: "Pakistan")
Destination.create(country: "Palau")
Destination.create(country: "Panama")
Destination.create(country: "Papua New Guinea")
Destination.create(country: "Paraguay")
Destination.create(country: "Peru")
Destination.create(country: "Philippines")
Destination.create(country: "Poland")
Destination.create(country: "Portugal")
Destination.create(country: "Qatar")
Destination.create(country: "Romania")
Destination.create(country: "Russian Federation")
Destination.create(country: "Rwanda")
Destination.create(country: "St Kitts & Nevis")
Destination.create(country: "St Lucia")
Destination.create(country: "Saint Vincent & the Grenadines")
Destination.create(country: "Samoa")
Destination.create(country: "San Marino")
Destination.create(country: "Sao Tome & Principe")
Destination.create(country: "Saudi Arabia")
Destination.create(country: "Senegal")
Destination.create(country: "Serbia")
Destination.create(country: "Seychelles")
Destination.create(country: "Sierra Leone")
Destination.create(country: "Singapore")
Destination.create(country: "Slovakia")
Destination.create(country: "Slovenia")
Destination.create(country: "Solomon Islands")
Destination.create(country: "Somalia")
Destination.create(country: "South Africa")
Destination.create(country: "South Sudan")
Destination.create(country: "Spain")
Destination.create(country: "Sri Lanka")
Destination.create(country: "Sudan")
Destination.create(country: "Suriname")
Destination.create(country: "Swaziland")
Destination.create(country: "Sweden")
Destination.create(country: "Switzerland")
Destination.create(country: "Syria")
Destination.create(country: "Taiwan")
Destination.create(country: "Tajikistan")
Destination.create(country: "Tanzania")
Destination.create(country: "Thailand")
Destination.create(country: "Togo")
Destination.create(country: "Tonga")
Destination.create(country: "Trinidad & Tobago")
Destination.create(country: "Tunisia")
Destination.create(country: "Turkey")
Destination.create(country: "Turkmenistan")
Destination.create(country: "Tuvalu")
Destination.create(country: "Uganda")
Destination.create(country: "Ukraine")
Destination.create(country: "United Arab Emirates")
Destination.create(country: "United Kingdom")
Destination.create(country: "United States")
Destination.create(country: "Uruguay")
Destination.create(country: "Uzbekistan")
Destination.create(country: "Vanuatu")
Destination.create(country: "Vatican City")
Destination.create(country: "Venezuela")
Destination.create(country: "Vietnam")
Destination.create(country: "Yemen")
Destination.create(country: "Zambia")
Destination.create(country: "Zimbabwe")

